chess/urls.py
from django.conf.urls import patterns, include, url
import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
import views
admin.autodiscover()

urlpatterns = patterns('',

    # Examples:
    # url(r'^$', 'chess.views.home', name='home'),
    # url(r'^chess/', include('chess.foo.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:

    url(r'^$', views.tournaments, name='tournaments'),
    url(r'^players/$', views.all_players, name='all_players'),
    url(r'^tournaments/(?P<tournament_id>\d+)/?$', views.get_curr_tournament, name='curr_tournament'),
    url(r'^tournaments/(?P<tournament_id>\d+)/results$', views.get_curr_tournament_results, name='curr_tournament_results'),
    url(r'^tournaments/(?P<tournament_id>\d+)/step/(?P<tournament_step>\d+)$',
        views.get_curr_tournament_step, name='curr_tournament_step'),
    url(r'^add_participant/', views.add_player, name='add_player'),
    url(r'^tournaments/(?P<tournament_id>\d+)/add_players_to_trt/', views.add_players_to_trt, name='add_player_to_trt'),
    url(r'^change_result/(?P<part_id>\d+)', views.change_result, name='change_result'),
    url(r'^add_tournament/', views.add_tournament, name='add_tournament'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                           {'document_root': settings.MEDIA_ROOT}),
    url(r'^admin/', include(admin.site.urls))
)

chess/models.py
from django.db import models
from constants import SEX_CHOICES, WIN_CHOICES

__author__ = 'kozhuhds'

class Tournament(models.Model):
    name = models.CharField(max_length=60)
    date = models.DateField()
    description = models.CharField(max_length=200, default="empty")
    step = models.IntegerField(default=0)
    def __str__(self):
        return self.name


class Player(models.Model):
    tournament = models.ManyToManyField(Tournament, default=None)
    name = models.CharField(max_length=50)
    rating = models.IntegerField(default=0)
    sex = models.CharField(choices=SEX_CHOICES, max_length=6, default="MALE")
    prev_result = models.IntegerField(default=0)
    b_koef = models.IntegerField(default=0)
    def __str__(self):
        return self.name

class Part(models.Model):
    first_player = models.ForeignKey(Player, related_name='first_player')
    second_player = models.ForeignKey(Player, related_name='second_player')
    tournament = models.ForeignKey(Tournament, related_name="part_of_tournament")
    result  = models.IntegerField(choices = WIN_CHOICES, default=-1)
    tournament_step = models.IntegerField(default=0)
    is_served = models.BooleanField(default=False)

class Scores(models.Model):
    player = models.ForeignKey(Player, related_name="player_scores")
    tournament = models.ForeignKey(Tournament)
    value = models.FloatField(default=0)

templates/add_player_error.html
{% extends "base.html" %}

{% block content %}
    <script type="text/javascript">
        $(document).ready(function(){
            $('#add-user').on('click', function(){
                $('#add-user-modal').modal('show');
            });
            $('.choose-tr').dropdown({
                onChange: function(value){
                    $('#trt').val($(this).find('.item.active').attr('id'));
                }
            });

            $('.ui.radio.checkbox').checkbox();
        });
    </script>
     <div class="content error-validation-form">
            <h2>Add player</h2>
             <form action="{%url 'add_player'%}" method="post" name="add-user">
                {% csrf_token %}
                <div class="ui form segment">
                  <div class="field {%if form.name.errors %}error{% endif %}">
                    <label>Username</label>
                    <div class="ui left labeled icon input">
                      <input type="text" name="name" placeholder="Username" value="{{form.name.value}}">
                       {{form.name.errors}}
                      <i class="user icon"></i>
                      <div class="ui corner label">
                        <i class="icon asterisk"></i>
                      </div>
                    </div>
                  </div>
                  <div class="field {%if form.rating.errors%}error{%endif%}">
                    <label>ELO rating</label>
                    <div class="ui left labeled icon input">
                      <input type="text" name="rating" placeholder="ELO rating" value="{{form.rating.value}}">
                      {{form.rating.errors}}
                      <i class="signal icon"></i>
                      <div class="ui corner label">
                        <i class="icon asterisk"></i>
                      </div>
                    </div>
                  </div>
                  <div class="field">
                      <div class="ui radio checkbox">
                        <input type="radio" name="sex" checked>
                        <label>Male</label>
                      </div>
                  </div>
                  <div class="field">
                      <div class="ui radio checkbox">
                        <input type="radio" name="sex">
                        <label>Female</label>
                      </div>
                  </div>
                  <div class="ui error message">
                    <div class="header">We noticed some issues</div>
                  </div>
                </div>
          </form>
                 <div class="actions">
            <div class="ui buttons">
              <div onClick="document.forms['add-user'].submit();" class="ui positive button">Add player</div>
            </div>
        </div>
          </div>

{% endblock %}

templates/add_tournament_error.html
{% extends "base.html" %}

{% load url from future %}


{% block content %}
        <h2>Add tournament</h2>
          <div class="content error-validation-form">
             <form id="add-t-form" class="ui form" action="{%url 'add_tournament'%}" method="post" name="add-tournament">
                {% csrf_token %}
                <div class="ui form segment">
                  <div class="field {%if form.name.errors %}error{% endif %}">
                    <label>Name</label>
                    <div class="ui left labeled icon input">
                      <input type="text" name="name" placeholder="Name" value="{{form.name.value}}">
                      <i class="flag icon"></i>
                      <div class="ui corner label">
                        <i class="icon asterisk"></i>
                      </div>
                    </div>
                      {{form.name.errors}}
                  </div>
                  <div class="field {%if form.startdate.errors %}error{% endif %}">
                    <label>Date</label>
                    <div class="ui left labeled icon input">
                      <input type="date" name="startdate" placeholder="Start date" value="{{form.startdate.value}}">
                      <i class="time icon"></i>
                      <div class="ui corner label">
                        <i class="icon asterisk"></i>
                      </div>
                    </div>
                        {{form.startdate.errors}}
                  </div>
                  <div class="field {%if form.description.errors %}error{% endif %}">
                    <label>Description</label>
                    <div class="ui left labeled icon input">
                      <input type="text" name="description" placeholder="Description" value="{{form.description.value}}">
                      <i class="info icon"></i>
                      <div class="ui corner label">
                        <i class="icon asterisk"></i>
                      </div>
                    </div>
                      {{form.description.errors}}

                  </div>
                  <div class="ui error message">
                    <div class="header">We noticed some issues</div>
                  </div>
                </div>
          </form>
          <div class="actions">
            <div class="ui buttons">
              <div class="ui submit positive button" onClick="document.forms['add-tournament'].submit();">Add tournament</div>
            </div>
          </div>
          </div>
{% endblock %}

templates/all_participants.html
{% extends "base.html" %}
{% load url from future %}

{% block content %}
    <script type="text/javascript">
        $(document).ready(function(){
            $('#add-user').on('click', function(){
                $('#add-user-modal').modal('show');
            });
            $('.ui.radio.checkbox').checkbox();
        });
    </script>
<div class="ui celled grid">
<table class="ui table segment">
  <thead>
    <tr>
        <th>Name</th>
        <th>ELO rating</th>
    </tr>
  </thead>
  <tbody>
  {% if player_list|length = 0 %}
  <tr><td>Click add participant to create player</td></tr>
  {% else %}
  {%for player in player_list%}
    <tr>
      <td>{{player.name}}</td>
      <td>{{player.rating}}</td>
    </tr>
  {%endfor%}
  </tbody>
  {% endif %}
  {% if user.is_authenticated %}
  <tfoot>
    <tr><th colspan="3">
      <div id="add-user" class="ui teal labeled icon button"><i class="user icon"></i> Add participant</div>
      <div id="add-user-modal" class="ui modal small transition scrolling">
          <i class="close icon"></i>
          <div class="header">
            Add participant
          </div>
          <div class="content">
             <form action="{%url 'add_player'%}" method="post" name="add-user">
                {% csrf_token %}
                <div class="ui form segment">
                  <div class="field">
                    <label>Username</label>
                    <div class="ui left labeled icon input">
                      <input type="text" name="name" placeholder="Username">
                      <i class="user icon"></i>
                      <div class="ui corner label">
                        <i class="icon asterisk"></i>
                      </div>
                    </div>
                  </div>
                  <div class="field">
                    <label>ELO rating</label>
                    <div class="ui left labeled icon input">
                      <input type="text" name="rating" placeholder="ELO rating">
                      <i class="signal icon"></i>
                      <div class="ui corner label">
                        <i class="icon asterisk"></i>
                      </div>
                    </div>
                  </div>
                  <div class="field">
                      <div class="ui radio checkbox">
                        <input type="radio" name="sex" checked>
                        <label>Male</label>
                      </div>
                  </div>
                  <div class="field">
                      <div class="ui radio checkbox">
                        <input type="radio" name="sex">
                        <label>Female</label>
                      </div>
                  </div>
                  <div class="ui error message">
                    <div class="header">We noticed some issues</div>
                  </div>
                </div>
          </form>
          </div>
          <div class="actions">
            <div class="ui buttons">
              <div class="ui button red">Cancel</div>
              <div class="or"></div>
              <div onClick="document.forms['add-user'].submit();" class="ui positive button">Add</div>
            </div>
          </div>
      </div>
    </th>
  </tr>
  </tfoot>
   {% endif %}
</table>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset=utf-8 />
	<title>Chess tournament</title>
	<link rel="stylesheet" type="text/css" media="screen" href="{{MEDIA_URL}}semantic/minified/collections/menu.min.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="{{MEDIA_URL}}semantic/minified/elements/basic.min.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="{{MEDIA_URL}}semantic/minified/elements/input.min.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="{{MEDIA_URL}}semantic/minified/elements/label.min.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="{{MEDIA_URL}}semantic/minified/elements/button.min.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="{{MEDIA_URL}}semantic/minified/elements/icon.min.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="{{MEDIA_URL}}semantic/minified/elements/step.min.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="{{MEDIA_URL}}semantic/minified/collections/table.min.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="{{MEDIA_URL}}semantic/minified/collections/form.min.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="{{MEDIA_URL}}semantic/minified/modules/modal.min.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="{{MEDIA_URL}}semantic/minified/modules/dimmer.min.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="{{MEDIA_URL}}semantic/minified/modules/dropdown.min.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="{{MEDIA_URL}}semantic/minified/modules/transition.min.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="{{MEDIA_URL}}semantic/minified/modules/checkbox.min.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="{{MEDIA_URL}}semantic/minified/collections/table.min.css" />
    <!--{% block additional_css %}{% endblock %}-->
	<link rel="stylesheet" type="text/css" media="screen" href="{{MEDIA_URL}}semantic/semantic.css" />
	<script type="text/javascript" src="{{MEDIA_URL}}js/jquery.min.js"></script>
	<script type="text/javascript" src="{{MEDIA_URL}}js/jquery.easing.1.3.js"></script>
	<script type="text/javascript" src="{{MEDIA_URL}}semantic/minified/modules/modal.js"></script>
	<script type="text/javascript" src="{{MEDIA_URL}}semantic/minified/modules/dimmer.js"></script>
	<script type="text/javascript" src="{{MEDIA_URL}}semantic/minified/modules/dropdown.js"></script>
	<script type="text/javascript" src="{{MEDIA_URL}}semantic/minified/modules/transition.js"></script>
	<script type="text/javascript" src="{{MEDIA_URL}}semantic/minified/modules/checkbox.min.js"></script>
	<script type="text/javascript" src="{{MEDIA_URL}}semantic/minified/modules/behavior/form.min.js"></script>
	<!--[if IE]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>
<body class="left pushed">
<!--<a class="ui green button"><i class="add sign layout icon"></i>Add player</a>-->
<div class="ui floating vertical sidebar menu active">
  <a href="/" class="{% if tr_active %} active {% endif %} item">
    <i class="tasks icon"></i>
    Tournament
  </a>
  <a href="/players" class="{% if pl_active %} active {% endif %} item">
    <i class="users icon"></i>
    All players
  </a>
</div>
    {% block content %}{% endblock %}
</body>
</html>

templates/curr_tournament.html
{% extends "base.html" %}
{% load url from future %}

{% block content %}
<script type="text/javascript">
    $(document).ready(function(){
        $('#add-user').on('click', function(){
            $('#add-user-modal').modal('show');
        });
        $('.ui.checkbox').checkbox()
    });
</script>
  <h1>{{tournament.name}}</h1>
  <h2>Description: {{tournament.description}}</h2>
  <div class="ui small steps">
  {% if steps|length < 1 %}
      {% if player_list|length > 1 and user.is_authenticated %}
        <a href="{{tournament.id}}/step/1" class="ui step">Start tournament</a>
      {% else %}
        <a href="#" class="ui step disabled" title="Add players to this tournament to start tournament">Start tournament</a>
      {% endif %}
  {% else %}
  {% for st in steps %}
      <a href="{{tournament.id}}/step/{{st}}" class="ui step">
        Step {{st}}
      </a>
  {% endfor %}
  {% endif %}
  {% if tournament_is_end %}
  <a href="/tournaments/{{tournament.id}}/results" class="ui step">
      Tournament results
  </a>
 {% endif %}
  </div>
  <h3>List of players</h3>
<table class="ui table segment">
    <thead>
        <tr>
           <th>Name</th>
           <th>Rating ELO</th>
           <th>Scores</th>
        </tr>
    </thead>
    <tbody>
    {% if player_list|length = 0%}
        <tr><td>Click 'add player' to add player to this tournament</td></tr>
    {% else %}
        {%for player in player_list%}
            <tr>
                <td>{{player.name}}</td>
                <td>{{player.rating}}</td>
                <td>{{player.scores}}</td>
            </tr>
        {% endfor %}
    {% endif %}
    </tbody>
    {% if user.is_authenticated and tournament.step = 0 %}
    <tfoot>
        <tr>
            <td>
                <div id="add-user" class="ui teal labeled icon button"><i class="level up icon"></i> Add player</div>
                      <div id="add-user-modal" class="ui modal small transition scrolling">
          <i class="close icon"></i>
          <div class="header">
            Add participant
          </div>
          <div class="content">
             <form action="{{tournament.id}}/add_players_to_trt/" method="post" name="add-user-to-trt">
                {% csrf_token %}
                <div class="ui form segment">
                    {% if players_list_exclude|length = 0%}
                       Empty. All users added.
                    {% else %}
                    <table class="table ui segment">
                        <thead>
                            <th>Add</th>
                            <th>Player</th>
                            <th>ELO rating</th>
                        </thead>
                        {% for pl in players_list_exclude%}
                        <tr>
                            <td>
                                <div class="ui checkbox">
                                    <input id="{{pl.id}}" type="checkbox" name="{{pl.id}}">
                                    <label>{{pl.name}}</label>
                                </div>
                            </td>
                            <td>{{pl.name}}</td>
                            <td>{{pl.rating}}</td>
                        </tr>
                        {% endfor %}
                    </table>
                    {% endif %}
                </div>
             </form>
          </div>
          <div class="actions">
            <div class="ui buttons">
              <div class="ui button red">Cancel</div>
              <div class="or"></div>
              <div onClick="document.forms['add-user-to-trt'].submit();" class="ui positive button">Add</div>
            </div>
          </div>
      </div>
            </td>
        </tr>
    </tfoot>
    {% endif %}
 </table>
{% endblock %}

templates/curr_tournament_step.html
{% extends "base.html" %}
{% load url from future %}

{% block content %}
<script type="text/javascript">
    $(document).ready(function(){
    {% if user.is_authenticated %}
        $('.edit-result').dropdown({
                onChange: function(value){
                    $(this).find('.curr-result').val($(this).find('.item.active').attr('res'));
                    $(this).find('form').submit();
                }
        });
    {% endif %}
    });
</script>
  <h1>{{tournament.name}}</h1>
 {%if message %}
    <h2>{{message}}</h2>
 {% else %}
 <div class="ui small steps">
      {% for st, active in steps %}
            {%if active%}
                <a href="{{st}}" class="ui step active">Step {{st}}</a>
            {% else %}
                <a href="{{st}}" class="ui step">Step {{st}}</a>
            {% endif %}
      {% endfor %}
     {% if tournament_is_end %}
      <a href="/tournaments/{{tournament.id}}/results" class="ui step">
          Tournament results
      </a>
     {% endif %}
 </div>
  <h3>Parts</h3>
  <table class="ui table segment">
  <thead>
    <tr>
        <th>Game</th>
        <th>Result</th>
    </tr>
  </thead>
  <tbody>
  {%for part in part_list%}
    <tr>
      <td>{{part.first_player}} vs {{part.second_player}}</td>
      <td>
        <div class="ui dropdown inline edit-result">
          <form action="{% url 'change_result' part.id %}" method="post" name="change-result">
            {% csrf_token %}
            <input type="hidden" class="curr-result" name="result" value="-1">
            <input type="hidden" name="tournament_id" value="{{ tournament.id }}">
          </form>
          <div class="text">{{part.get_result_display}}</div>
          {% if user.is_authenticated %}
          <i class="dropdown icon"></i>
           {% endif %}
          <div class="menu">
            <div class="item" res="1">{{part.first_player}}'s win</div>
            <div class="item" res="2">{{part.second_player}}'s win</div>
            <div class="item" res="0">Draw</div>
          </div>
        </div>
      </td>
    </tr>
  {%endfor%}
  </tbody>
  <tfoot>
    <tr><th colspan="3">
    </th>
  </tr></tfoot>
</table>
<h3>Players</h3>
<table class="ui table segment">
    <thead>
        <tr>
           <th>Name</th>
           <th>Scores</th>
           <th>ELO rating</th>
        </tr>
    </thead>
    <tbody>
        {%for player in player_list%}
            <tr>
                <td>{{player.name}}</td>
                <td>{{player.scores}}</td>
                <td>{{player.rating}}</td>
            </tr>
        {% endfor %}
    </tbody>
 </table>
{% endif %}
{% endblock %}

templates/final_results.html
{% extends "base.html" %}
{% load url from future %}

{% block content %}
<script type="text/javascript">
    $(document).ready(function(){
        $('.edit-result').dropdown({
                onChange: function(value){
                    $(this).find('.curr-result').val($(this).find('.item.active').attr('res'));
                    $(this).find('form').submit();
                }
        });
    });
</script>
  <h1>{{tournament.name}}</h1>
 <div class="ui small steps">
       {% for st, active in steps %}
            {%if active%}
                <a href="step/{{st}}" class="ui step active">Step {{st}}</a>
            {% else %}
                <a href="step/{{st}}" class="ui step">Step {{st}}</a>
            {% endif %}
      {% endfor %}
      <a href="" class="ui step active">
          Tournament results
      </a>
 </div>
<h3>Players places</h3>
<table class="ui table segment">
    <thead>
        <tr>
           <th>Place</th>
           <th>Name</th>
           <th>Scores</th>
           <th>ELO rating</th>
        </tr>
    </thead>
    <tbody>
        {%for player in player_list%}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{player.name}}</td>
                <td>{{player.scores}}</td>
                <td>{{player.rating}}</td>
            </tr>
        {% endfor %}
    </tbody>
 </table>
{% endblock %}

templates/parts.html
{% extends "base.html" %}

{% block content %}
<script type="text/javascript">
    $(document).ready(function(){
        $('.edit-result').dropdown();
    });
</script>
  <table class="ui table segment">
  <thead>
    <tr>
        <th>Game</th>
        <th>Result</th>
    </tr>
  </thead>
  <tbody>
  {%for part in part_list%}
    <tr>
      <td>{{part.first_player}} vs {{part.second_player}}</td>
      <td>
        <div class="ui dropdown inline edit-result">
          <div class="text">{%if part.result%} {{part.result}} {%else%} Result {%endif%}</div>
          <i class="dropdown icon"></i>
          <div class="menu">
            <div class="item">{{part.first_player}}'s win</div>
            <div class="item">{{part.second_player}}'s win</div>
            <div class="item">Draw</div>
          </div>
        </div>
      </td>
    </tr>
  {%endfor%}
  </tbody>
  <tfoot>
    <tr><th colspan="3">
    </th>
  </tr></tfoot>
</table>
{% endblock %}

templates/tournaments.html
{% extends "base.html" %}
{% load url from future %}


{% block content %}
<script type="text/javascript">
    $(document).ready(function(){
        $('.edit-result').dropdown();
        $('#add-tournament').on('click', function(){
            $('#add-tournament-modal').modal('show');
        });
    });
</script>
  <table class="ui table segment">
  <thead>
    <tr>
        <th>Tournament name</th>
        <th>Date</th>
        <th>Description</th>
    </tr>
  </thead>
  <tbody>
  {% if tournaments_list %}
      {%for tr in tournaments_list%}
        <tr>
          <td><a style="text-decoration: underline" href="/tournaments/{{tr.id}}">{{tr.name}}</a></td>
          <td>{{tr.date}}</td>
          <td>{{tr.description}}</td>
        </tr>
      {%endfor%}
  {% else %}
    <tr>
      <td>Empty. Click 'add tournament' to create new chess tournament.</td>
    </tr>
  {% endif %}
  </tbody>
  {% if user.is_authenticated %}

<tfoot>
    <tr><th colspan="3">
      <div id="add-tournament" class="ui teal labeled icon button"><i class="plus icon"></i> Add tournament</div>
      <div id="add-tournament-modal" class="ui modal small transition scrolling">
          <i class="close icon"></i>
          <div class="header">
            Add tournament
          </div>
          <div class="content">
             <form id="add-t-form" class="ui form" action="{%url 'add_tournament'%}" method="post" name="add-tournament">
                {% csrf_token %}
                <div class="ui form segment">
                  <div class="field">
                    <label>Name</label>
                    <div class="ui left labeled icon input">
                      <input type="text" name="name" placeholder="Name" required>
                      <i class="flag icon"></i>
                      <div class="ui corner label">
                        <i class="icon asterisk"></i>
                      </div>
                    </div>
                  </div>
                  <div class="field">
                    <label>Date</label>
                    <div class="ui left labeled icon input">
                      <input type="date" name="startdate" placeholder="Start date" required>
                      <i class="time icon"></i>
                      <div class="ui corner label">
                        <i class="icon asterisk"></i>
                      </div>
                    </div>
                  </div>
                  <div class="field">
                    <label>Description</label>
                    <div class="ui left labeled icon input">
                      <input type="text" name="description" placeholder="Description" required>
                      <i class="info icon"></i>
                      <div class="ui corner label">
                        <i class="icon asterisk"></i>
                      </div>
                    </div>
                  </div>
                  <div class="ui error message">
                    <div class="header">We noticed some issues</div>
                  </div>
                </div>
          </form>
          </div>
          <div class="actions">
            <div class="ui buttons">
              <div class="ui button red">Cancel</div>
              <div class="or"></div>
              <div class="ui submit positive button" onClick="document.forms['add-tournament'].submit();">Add</div>
            </div>
          </div>
      </div>
    </th>
  </tr>
  </tfoot>
  {% endif %}
</table>
{% endblock %}